version: "3.3"

services:

  tdb:
    # Triple-store DataBase
    build: ./tdb
    ports:
      - 3030:3030
    # volumes:
    #   - ./tdb/data:/fuseki/data

  # pitium:
  #   build: ./pitium
  #   volumes:
  #     - ./code:/pitium
  #   depends_on:
  #     - tdb
