name: tesi
channels:
  - https://conda.anaconda.org/menpo
  - conda-forge
dependencies:
  - python==3.7.6
  - numpy==1.18.5
  - pytorch==1.5.0
  - jep==3.9.0
  - pip
  - pip:
    - transformers==2.5.1
